---
new_page_extension: md
auto_deploy: false
admin_path: src/admin
webhook_url: 
sections:
- type: directory
  path: src/cases
  label: Cases
  create: all
  match: "**/*"
  exclude: "*.json"
  templates:
  - cases
- type: directory
  path: src/members
  label: Members
  create: all
  match: "**/*"
  exclude: "*.json"
  templates:
  - members
- type: directory
  path: src/sections
  label: Content
  create: all
  match: "**/*"
  exclude: "*.json"
  templates:
  - section-content
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: preview
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npx @11ty/eleventy
